default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  password: 123456
development:
  <<: *default
  database: sample_social_development
test:
  <<: *default
  database: sample_social_test
  username: cybergarage
production:
  <<: *default
  database: sample_social_production
  username: cybergarage
  password: 123456
  # password: <%= ENV['EVENT_DATABASE_PASSWORD'] %>
